### ISSUE TITLE
La opción "Look at on Title" no se desactiva

### ISSUE THREAD

**Issue by manuelge** [etruel/etruel-del-post-copies#2]
Amigos un usuario reportó un pequeño issue en el plugin y pude comprobarlo, la opción "Look at on Title" no se desactiva.
Can't deactivate "Look at on Title" checkbox.  After update the campaign it appears checked again.

**Comment by younes-dro** [comment]
The plugin must always keep the "Look at on Title" checkbox checked.

**Comment by younes-dro** [comment]
> Amigos un usuario reportó un pequeño issue en el plugin y pude comprobarlo, la opción "Look at on Title" no se desactiva.
> Can't deactivate "Look at on Title" checkbox. After update the campaign it appears checked again.

The current logic of the Plugin is to keep at least the "Look at on Title" box always active
