### ISSUE TITLE
Exclude Posts (types) by ID

### ISSUE THREAD

**Issue by manuelge** [etruel/etruel-del-post-copies#4]
I was doing some tests and found a couple of issues with this feature.

As you know, it can be configured from Del Campaigns>Settings or directly from the Campaign, however the issues are different depending on where it is configured.

**If configured from Settings** it just doesn't work, it keeps deleting the posts you are trying to exclude.

**If configured from the Campaign** it does not get any posts to delete, it can be viewed from the table of post copies.

However, **when both fields are configured** (in settings and in the campaign) using the same IDs it works correctly.

Regards,
Manuel

**Comment by younes-dro** [comment]
code is updated to support all cases:
`                        $allids = array();
                        if(empty($wpedpc_campaign->excluded_ids) && empty($excluded_posts) && empty( $wpedpc_options['excluded_ids'])){
                            $excluded_ids = '-1';
                        }else{
                            if( isset($wpedpc_campaign->excluded_ids) and !empty($wpedpc_campaign->excluded_ids)){

                                array_push($allids, maybe_serialize($wpedpc_campaign->excluded_ids));
                              
                            }
                            if( isset($excluded_posts) && !empty($excluded_posts)){

                                array_push($allids, maybe_serialize($excluded_posts));
                                
                            }
                            if( isset($wpedpc_options['excluded_ids']) && !empty($wpedpc_options['excluded_ids'])){

                                array_push($allids, maybe_serialize ($wpedpc_options['excluded_ids']));
                               
                            } 
                            $ids = implode(',',$allids );
                            $k = 0;
                            $len = count($allids);
                            foreach ($allids as $id) {
                             if( $k < $len - 1){
                                 $excluded_ids .= $id .',';
                             }else{
                                 $excluded_ids .= $id;
                             }
                            $k++;

                            }
                                                        
                        }`

**Comment by etruel** [comment]
Great Younes, before close the issue, what is the purpose of line 238 ? Can we delete it?
 update_option('sql', $query);

**Comment by younes-dro** [comment]
Yes delete it . I've forgotten. I just used it to see the request being executed
